apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: otbbu07iq-python
  janus-idp.io/tekton: otbbu07iq-python
  backstage.io/kubernetes-id: otbbu07iq-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: otbbu07iq-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
